name: flappy_ember
description: A simple flappy birds-like game
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flame: ^1.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.1.3
  flame_test: ^1.9.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/boxes/
    - assets/images/
